apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-deployment
  template:
    metadata:
      labels:
        app: cicd-deployment
    spec:
      containers:
      - name: cicd-deployment
        image: nitishsancs/Jenkins-CICD
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cicd-service
spec:
  selector:
    app: cicd-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
